# Generated by Django 5.1.6 on 2025-02-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('available_days', models.CharField(max_length=50)),
                ('available_time', models.CharField(max_length=20)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
